# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.4

# Default target executed when no arguments are given to make.
default_target: all

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/home/bschubert/src/unionfs/unionfs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/home/bschubert/src/unionfs/unionfs

# Include the progress variables for this target.
include CMakeFiles/progress.make

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/home/bschubert/src/unionfs/unionfs/CMakeFiles $(CMAKE_ALL_PROGRESS)
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/home/bschubert/src/unionfs/unionfs/CMakeFiles 0

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean

# The main clean target
clean/fast: clean

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1

#=============================================================================
# Target rules for targets named unionfs

# Build rule for target.
unionfs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unionfs

# fast build rule for target.
unionfs/fast:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/build

# target to build an object file
cow.o:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/cow.o

# target to preprocess a source file
cow.i:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/cow.i

# target to generate assembly for a file
cow.s:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/cow.s

# target to build an object file
cow_utils.o:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/cow_utils.o

# target to preprocess a source file
cow_utils.i:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/cow_utils.i

# target to generate assembly for a file
cow_utils.s:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/cow_utils.s

# target to build an object file
debug.o:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/debug.o

# target to preprocess a source file
debug.i:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/debug.i

# target to generate assembly for a file
debug.s:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/debug.s

# target to build an object file
elfhash.o:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/elfhash.o

# target to preprocess a source file
elfhash.i:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/elfhash.i

# target to generate assembly for a file
elfhash.s:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/elfhash.s

# target to build an object file
findbranch.o:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/findbranch.o

# target to preprocess a source file
findbranch.i:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/findbranch.i

# target to generate assembly for a file
findbranch.s:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/findbranch.s

# target to build an object file
general.o:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/general.o

# target to preprocess a source file
general.i:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/general.i

# target to generate assembly for a file
general.s:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/general.s

# target to build an object file
hash.o:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/hash.o

# target to preprocess a source file
hash.i:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/hash.i

# target to generate assembly for a file
hash.s:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/hash.s

# target to build an object file
hashtable.o:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/hashtable.o

# target to preprocess a source file
hashtable.i:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/hashtable.i

# target to generate assembly for a file
hashtable.s:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/hashtable.s

# target to build an object file
hashtable_itr.o:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/hashtable_itr.o

# target to preprocess a source file
hashtable_itr.i:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/hashtable_itr.i

# target to generate assembly for a file
hashtable_itr.s:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/hashtable_itr.s

# target to build an object file
opts.o:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/opts.o

# target to preprocess a source file
opts.i:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/opts.i

# target to generate assembly for a file
opts.s:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/opts.s

# target to build an object file
readdir.o:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/readdir.o

# target to preprocess a source file
readdir.i:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/readdir.i

# target to generate assembly for a file
readdir.s:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/readdir.s

# target to build an object file
rmdir.o:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/rmdir.o

# target to preprocess a source file
rmdir.i:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/rmdir.i

# target to generate assembly for a file
rmdir.s:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/rmdir.s

# target to build an object file
stats.o:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/stats.o

# target to preprocess a source file
stats.i:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/stats.i

# target to generate assembly for a file
stats.s:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/stats.s

# target to build an object file
string.o:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/string.o

# target to preprocess a source file
string.i:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/string.i

# target to generate assembly for a file
string.s:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/string.s

# target to build an object file
unionfs.o:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/unionfs.o

# target to preprocess a source file
unionfs.i:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/unionfs.i

# target to generate assembly for a file
unionfs.s:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/unionfs.s

# target to build an object file
unlink.o:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/unlink.o

# target to preprocess a source file
unlink.i:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/unlink.i

# target to generate assembly for a file
unlink.s:
	$(MAKE) -f CMakeFiles/unionfs.dir/build.make CMakeFiles/unionfs.dir/unlink.s

# Help Target
help::
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... unionfs"
	@echo "... cow.o"
	@echo "... cow.i"
	@echo "... cow.s"
	@echo "... cow_utils.o"
	@echo "... cow_utils.i"
	@echo "... cow_utils.s"
	@echo "... debug.o"
	@echo "... debug.i"
	@echo "... debug.s"
	@echo "... elfhash.o"
	@echo "... elfhash.i"
	@echo "... elfhash.s"
	@echo "... findbranch.o"
	@echo "... findbranch.i"
	@echo "... findbranch.s"
	@echo "... general.o"
	@echo "... general.i"
	@echo "... general.s"
	@echo "... hash.o"
	@echo "... hash.i"
	@echo "... hash.s"
	@echo "... hashtable.o"
	@echo "... hashtable.i"
	@echo "... hashtable.s"
	@echo "... hashtable_itr.o"
	@echo "... hashtable_itr.i"
	@echo "... hashtable_itr.s"
	@echo "... opts.o"
	@echo "... opts.i"
	@echo "... opts.s"
	@echo "... readdir.o"
	@echo "... readdir.i"
	@echo "... readdir.s"
	@echo "... rmdir.o"
	@echo "... rmdir.i"
	@echo "... rmdir.s"
	@echo "... stats.o"
	@echo "... stats.i"
	@echo "... stats.s"
	@echo "... string.o"
	@echo "... string.i"
	@echo "... string.s"
	@echo "... unionfs.o"
	@echo "... unionfs.i"
	@echo "... unionfs.s"
	@echo "... unlink.o"
	@echo "... unlink.i"
	@echo "... unlink.s"



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0

